### ISSUE TITLE
Add support to build for guest customization or cloud-init for Linux distributions

### ISSUE THREAD

**Issue by danielhanaj** [vmware-samples/packer-examples-for-vsphere#269]
### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/CODE_OF_CONDUCT.md).

### Community Note
- Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- Do not leave "+1" or other comments that do not add relevant information or questions.
- If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

After successful deployment from Ubuntu images, static IP configuration is overwritten by cloud-init during next reboot. Netplan config file state that /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg should be created with fallowing entry to disable it: 

network: {config: disabled}

Would be great to add ansible script that creates such file on Ubuntu 20.04 and 22.04 at the end of building process.

### Use Case(s)

Deoloy VM to production environment

### Potential Configuration

Ansible playbook that creates /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with network: {config: disabled} entry.

**Comment by tenthirtyam** [comment]
Essentially, add support to toggle for guest customization vs cloud-init.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
The enhancement title has been updated to reflect the enhancement outcome.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by danielhanaj** [comment]
Hi Ryan,
At the beginning hhank you very much for great and useful project. Already given a GitHub Star.

When you say guest customization - do you mean VM Customization Specifications under Policies and Profiles in vSphere environment  when we can specify dedicated profile for Linux systems? If you do, is this the right link to apply necessary changes? https://kb.vmware.com/s/article/59557 
What if user needs to manually specify system name or static IP address without automatic guest customization? Last thing we want is to configure entire server manually and realize it lost it's IP after next planned reboot. This is happen right now after deploying fresh Ubuntu 20.04 and Ubuntu 22.04 from content library template.
Thanks

**Comment by tenthirtyam** [comment]
Yes, guest customization is the uses VM Tools.  If you use the attempt to apply guest customization to the Ubuntu 20.04 and 22.04 images, which are configured for cloud-init, those are lost on reboot. You'd need to modify the playbook to run something like:

```yaml
- name: "Allow Guest Customization with VMware Tools"
  shell: |
    touch /etc/cloud/cloud.cfg.d/99.disable-network-config.cfg
    echo "network: {config: disabled}" >> /etc/cloud/cloud.cfg.d/99.disable-network-config.cfg
  when: ansible_distribution_version == "20.04" or ansible_distribution_version == "22.04"
  args:
    warn: false
```

Ryan Johnson
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
