### ISSUE TITLE
[ENHANCEMENT] Use ansible provisioner for Linux configuration and packages

### ISSUE THREAD

**Issue by tenthirtyam** [vmware-samples/packer-examples-for-vsphere#54]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Use `ansible` provisioner for Linux configuration and packages.

### Use Case(s)

Cleaner management of configuration and packages for Linux machine images

**Comment by sestegra** [comment]
First, I suggest to divide playbook by OS family.

```
- name: "centos.yml"
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - include_tasks: playbook-redhat.yml
       when: ansible_os_family == 'RedHat'

    - include_tasks: playbook-debian.yml
       when: ansible_os_family == 'Debian'
```

Then, I suggest to do the same for Windows with WinRM access.
