### ISSUE TITLE
Add support for cloud-init for each Linux distribution

### ISSUE THREAD

**Issue by tenthirtyam** [vmware-samples/packer-examples-for-vsphere#691]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Add support for cloud-init for each Linux distribution, where applicable, by default with an option for guest tools override.

Note: Not all may support the cloud-init release with the VMware datasource.

### Use Case(s)

Add support for cloud-init for each Linux distribution, where applicable, by default with an option for guest tools override.

### Potential Configuration

```yaml
- name: Configuring cloud-init.
  become: true
  tasks:
    - name: Add cloud-init configuration
      copy:
        content: |
          disable_vmware_customization: false
          datasource:
            VMware:
              vmware_cust_file_max_wait: 20
        dest: /etc/cloud/cloud.cfg.d/99-vmware-guest-customization.cfg

    - name: Enable SSH password authentication in cloud-init configuration.
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^ssh_pwauth:'
        line: 'ssh_pwauth: 1'
```

However, dependent on the OS.
