### ISSUE TITLE
Add an option to perform builds using an Ansible playbook

### ISSUE THREAD

**Issue by tenthirtyam** [vmware-samples/packer-examples-for-vsphere#693]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Add an **option** to perform builds using an Ansible playbook.

### Use Case(s)

As Ansible is one of the most-used configuration management tools, I'm sure there would be a large pool of people who could contribute. I have much more skill in Ansible than in BASH (in fact, I rarely use BASH scripts any more) and the ansible toolset is more powerful.

### Potential Configuration

```yml
---

- name: Build a VMware template
  gather_facts: false
  become: false
  hosts: localhost
  vars:
    host_list:
      rocky9:
        input_path: "{{ script_path }}/builds/linux/rocky/9/"
    vars_files:
      - vsphere.pkrvars.hcl
      - build.pkrvars.hcl
      - ansible.pkrvars.hcl
      - proxy.pkrvars.hcl
      - common.pkrvars.hcl
    
  tasks:

  # Here we append each member of the var_files list into a packer_build_args variable via a loop.
  - name: Build the Packer command line:
    set_fact:
      packer_build_args: "{{ packer_build_args | default('') + '-var-file=\"' + item }} + ' '"
    loop: "{{ vars_files }}" 

  - name: "Initialize Packer."
    shell: "packer init {{ host_list[desired_host]['input_path']}" 

  - name: "Build a {{ desired_host }} host."
    shell: "packer build --force {{ host_list[desired_host]['input_path'}}" 
```

```bash
ansible-playbook -i localhost, build_vmware_image.yml -e 'desired_host=rocky_9'
```

### References

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
