### ISSUE TITLE
Simple solve for AlmaLinux 8 - Failed to validate GPG signature

### ISSUE THREAD

**Issue by shaneholloman** [vmware-samples/packer-examples-for-vsphere#852]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

The included ansible playbook works perfectly for builds of centos, redhat, rocky, oraclelinux versions 8 and 9, additionally it works for almalinux 9. but running the exact playbook we get this error on almalinux 8:

```sh
isioner-ansible3498492444 /home/<sensitive>/shane/git/it/vsphere-packer/ansible/linux-playbook.yml
    vsphere-iso.linux-almalinux:
    vsphere-iso.linux-almalinux: PLAY [all] *********************************************************************
    vsphere-iso.linux-almalinux:
    vsphere-iso.linux-almalinux: TASK [Gathering Facts] *********************************************************
    vsphere-iso.linux-almalinux: ok: [default]
    vsphere-iso.linux-almalinux:
    vsphere-iso.linux-almalinux: TASK [base : Update the operating system and install additional packages.] *****
    vsphere-iso.linux-almalinux: included: /home/<sensitive>/shane/git/it/vsphere-packer/ansible/roles/base/tasks/linux.yml for default
    vsphere-iso.linux-almalinux:
    vsphere-iso.linux-almalinux: TASK [base : Updating the operating system.] ***********************************
    vsphere-iso.linux-almalinux: fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for tzdata-2024a-1.el8.noarch: Public key for tzdata-2024a-1.el8.noarch.rpm is not installed"}
```

### Use Case(s)

Fix GPG keys for AlmaLinux 8

### Potential Configuration

```yml
# Red Hat Enterprise Linux or derivatives.

- name: "Checking the Red Hat Subscription Manager status."
  command:
    cmd: subscription-manager status
  register: result
  failed_when: "'ERROR' in result.stderr"
  when: ansible_distribution == 'RedHat'


# Add this right here immediately after the above which allow the os update to succeed later
- name: "Upgrade almalinux-release package."
  ansible.builtin.command:
    cmd: dnf upgrade -y almalinux-release
  become: true
  when: ansible_distribution == 'AlmaLinux'
```

> Patch applies to this file

[./ansible/roles/base/tasks/linux.yml](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/develop/ansible/roles/base/tasks/linux.yml)
