### ISSUE TITLE
Photon Build Failures

### ISSUE THREAD

**Issue by Kennochas** [vmware-samples/packer-examples-for-vsphere#853]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

latest

### VMware vSphere

7.0U3

### HashiCorp Packer

10.0.1

### HashiCorp Packer Plugin for VMware vSphere

1.2.1

### Guest Operating System

Photon

### Description

Currently, Photon is unable to build due to the following

```
    vsphere-iso.linux-photon: TASK [configure : lineinfile] **************************************************
    vsphere-iso.linux-photon: changed: [default]
    vsphere-iso.linux-photon:
    vsphere-iso.linux-photon: TASK [configure : Setting the hostname.] ***************************************
    vsphere-iso.linux-photon: fatal: [default]: FAILED! => {"changed": false, "msg": "hostname module cannot be used on platform Linux (Photon)"}
    vsphere-iso.linux-photon:
    vsphere-iso.linux-photon: PLAY RECAP *********************************************************************
    vsphere-iso.linux-photon: default                    : ok=13   changed=7    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0
    vsphere-iso.linux-photon:


```

### Expected Behavior

Build a photon template

### Actual Behavior

Build failure

### Steps to Reproduce

Run a photon build.
