### ISSUE TITLE
Rocky 9 installation failed when using vm_guest_os_cloudinit=true

### ISSUE THREAD

**Issue by a-belhadj** [vmware-samples/packer-examples-for-vsphere#950]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### VMware vSphere

8.0.3

### HashiCorp Packer

v1.11.1

### HashiCorp Packer Plugin for VMware vSphere

v1.3.0

### Guest Operating System

Rocky Linux 9

### Description

Bug here: https://github.com/vmware-samples/packer-examples-for-vsphere/blob/e33918344a068eb79c36afaf8119fc6cc2004ccd/ansible/roles/base/tasks/redhat.yml#L36

Ansible doc : You can use logical operators to combine conditions. When you have multiple conditions that all need to be true (that is, a logical and), you can specify them as a list.(https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html)

base_additional_packages are not installed when building a Rocky Linux because it doesnt validate the first condition (distribution == Fedora).

In version 0.20, similar issue occurs, cloud-init installation is always skipped for Rocky

### Expected Behavior

Tasks should not be skipped on Rocky system

### Actual Behavior

Tasks skipped because the condition is: 
"Fedora" AND "redhat>8"
instead of:
"Fedora" OR "redhat>8"

### Steps to Reproduce

Try to build a Rocky9 with cloud_init enabled

```hcl
// config/linux-rocky-9.pkrvars.hcl
vm_guest_os_cloudinit = true
```

### Log Fragments and Files

```
    vsphere-iso.linux-rocky: TASK [base : Getting guest operating system information.] **********************
    vsphere-iso.linux-rocky: ok: [default] => {
    vsphere-iso.linux-rocky:     "msg": "OS: Rocky 9.4"
    vsphere-iso.linux-rocky: }
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [base : Checking the Red Hat Subscription Manager status.] ****************
    vsphere-iso.linux-rocky: skipping: [default]
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [base : Upgrade almalinux-release package.] *******************************
    vsphere-iso.linux-rocky: skipping: [default]
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [base : Updating the operating system.] ***********************************
    vsphere-iso.linux-rocky: skipping: [default]
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [base : Installing additional packages.] **********************************
    vsphere-iso.linux-rocky: skipping: [default]
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [base : Installing cloud-init.] *******************************************
    vsphere-iso.linux-rocky: skipping: [default]
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [base : Updating the operating system.] ***********************************
    vsphere-iso.linux-rocky: skipping: [default]
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [base : Installing additional packages.] **********************************
    vsphere-iso.linux-rocky: skipping: [default]
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [base : Update the operating system and install additional packages.] *****
    vsphere-iso.linux-rocky: skipping: [default]
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [base : Update the operating system and install additional packages.] *****
    vsphere-iso.linux-rocky: skipping: [default]
    vsphere-iso.linux-rocky:
    vsphere-iso.linux-rocky: TASK [users : Configure the operating system users.] ***************************
    vsphere-iso.linux-rocky: included: /home/ubuntu/<sensitive>-examples-for-vsphere/<sensitive>/roles/users/tasks/linux.yml for default
    vsphere-iso.linux-rocky:
```
